apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-angular-app
data:
  config.production.json: |
    {
      "environmentName": "production",
      "endPointApiUrl": "{{ .Values.app.endPointApiUrl }}"
    }